USE locadora;

SET SQL_SAFE_UPDATES = 0;

# SELECIONA TODAS AS CLIENTES MULHERES
SELECT * FROM clientes WHERE cli_sexo = "F";

# DELETA TODOS OS CLIENTES QUE NÃO CADASTRARAM CPF
DELETE FROM clientes WHERE cli_cpf IS NULL;

# DA UM DESCONTO DE 20% EM TODOS OS FILMES QUE CUSTAM MAIS DE 5 REAIS
UPDATE filmes SET fil_preco = fil_preco * 0.8 WHERE fil_preco > 5;